make: get delete print
	gcc main.c -o main -g -std=gnu99 -Wall -Wextra
get:
	gcc get.c -o get -g -std=gnu99 -Wall -Wextra
delete:	
	gcc delete.c -o delete -g -std=gnu99 -Wall -Wextra
print:	
	gcc print.c -o print -g -std=gnu99 -Wall -Wextra
clean:
	rm main get delete print
